version: '3.3'
services:
  haskell-dev:
    image: bhongy/haskell-dev:8.6.2
    ports:
      - 8888:80
    volumes:
      - type: bind
        source: ./src
        target: /usr/app/src
        # read_only: true
    stdin_open: true
    tty: true