version: '3.3'
services:
  app:
    build: ./
    ports:
      - 8888:80
    volumes:
      - type: bind
        source: ./src
        target: /usr/app/src
        # read_only: true
    stdin_open: true
    tty: true