version: "3"
services:
  webapp:
    image: bhongy/vscode-remote-devcontainer.go:latest
    volumes:
      - ../..:/workspaces/docker-coding-sandbox:delegated
    depends_on:
      - db

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

  db:
    image: postgres:12.4-alpine
    restart: unless-stopped
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-password

# volumes:
#   postgres-data:
